version: "3.8"
services:
  core:
    container_name: core
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/var/www/core
      - ./public:/var/www/core/public
    networks:
      - network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/var/www/core/public
    ports:
      - "8000:80"
    depends_on:
      - core
    environment:
      NGINX_FPM_HOST: core
      NGINX_ROOT: /var/www/core/public
    networks:
      - network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: >
      --requirepass ${REDIS_PASSWORD}
    networks:
      - network

networks:
  network:
    driver: bridge